model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: comp
    cond_stage_key: comp
    image_size: 64
    channels: 48 # for u-net 
    concat_mode: true
    monitor: val/loss
    use_ema: false

    scheduler_config:
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: 1000
        max_decay_steps: 50000
        lr_start: 0.001
        lr_max: 0.1
        lr_min: 0.0001

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 96
        out_channels: 48 # 3 * 4 ** level of wavelet = 3 * 4 ** 2 = 48
        model_channels: 256
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_heads: 8
        resblock_updown: true

    first_stage_config:
      target: ldm.models.autoencoder.WaveModelInterface
      params:
        embed_dim: 3
        encoder_config:
          level: 2
          wavelet: haar
        decoder_config:
          level: 2
          wavelet: haar
          channel: 3

    cond_stage_config: __is_first_stage__


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    wrap: false
    train:
      target: ldm.data.iharmony4_dataset.Iharmony4Dataset
      params:
        dataset_root: dataset/ihm4/Hday2night
        is_for_train: true
        resize: 256
    validation:
      target: ldm.data.iharmony4_dataset.Iharmony4Dataset
      params:
        dataset_root: dataset/ihm4/Hday2night
        is_for_train: false
        resize: 256


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
